import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
import {PGlite,migration,manual,teacher,first,ale,schema} from './score_fixture.mjs';
const file=async n=>readFile(new URL('../migrations/'+n,import.meta.url),'utf8');
test('postures: repeated taps preserve attacks and defenders can attack',async()=>{
 const db=new PGlite();
 try{
  await db.exec(schema);await db.exec(migration);await db.exec(manual);
  for(const n of ['20260924_z_score_audit_and_undo.sql','20260924_zz_period_backups.sql','20260924_zzz_duel_arena.sql','20260924_zzz_duel_catalog.sql','20260925_arena_automatic_turns.sql','20260925_b_arena_spells.sql']) await db.exec(await file(n));
  const q=async(s,a=[])=>(await db.query(s,a)).rows[0]?.data;
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[teacher]);
  await q("select hechi.configurar_arena('TEST',true)");
  await db.query("select set_config('request.jwt.claim.sub','',false)");
  const invite=()=>q("select hechi.retar_arena('TEST',$1,'12345',$2,true) as data",[first,ale]);
  const accept=id=>q("select hechi.responder_reto_arena('TEST',$1,'12345',$2,true) as data",[ale,id]);
  let d=await accept((await invite()).id);
  await db.query("update hechi.duelos_arena set partida=jsonb_set(partida,'{a,apoyos,2}','{\"id\":\"hechizo-confundo\",\"uid\":\"trap\",\"oculta\":true}') where id=$1",[d.id]);
  const upgrade=await file('20260925_c_arena_battlefield.sql');
  await db.exec(upgrade);
  const view=async id=>(await q("select hechi.obtener_arena('TEST',$1,'12345') as data",[id])).activo;
  const action=(id,move,values={})=>q("select hechi.accion_duelo_arena('TEST',$1,'12345',$2,$3,$4,$5::jsonb) as data",[id,d.id,d.version,move,JSON.stringify(values)]);
  d=await view(first);
  assert.equal(d.yo.apoyos.length,5);assert.equal(d.yo.apoyos[2].id,'hechizo-confundo');
  assert.deepEqual(d.rival.apoyos,[null,null,null,null,null]);
  await db.exec(await file('20260925_d_arena_postures.sql'));
  d=await action(first,'rendirse');
  d=await accept((await invite()).id);
  assert.equal(d.yo.apoyos.length,5,'new matches also get five slots');
  const deck=await q('select hechi.arena_mazo() as data');
  const monster=(id,posicion='ataque')=>({id,uid:id,posicion,afinidad:'fuego',oculta:false,ataco:false,cambio:false});
  const a={vida:4000,mazo:deck.slice(0,20),mano:[{id:'hechizo-invisibilidad',uid:'spell'}],campo:[monster('dragon'),monster('doxy'),monster('gigante','defensa'),null,null],apoyos:[null,null,null,null,null]};
  const b={...a,mano:[],campo:[monster('bowtruckle'),null,null,null,null]};
  await db.query("update hechi.duelos_arena set partida=$2::jsonb where id=$1",[d.id,JSON.stringify({a,b,turno:'a',ronda:2,invoco:false,hechizo:false,fase:'invocacion'})]);
  d=await view(first);
  d=await action(first,'posicion',{casilla:0});assert.equal(d.yo.campo[0].posicion,'defensa');
  d=await action(first,'posicion',{casilla:0});assert.equal(d.yo.campo[0].posicion,'ataque');
  await assert.rejects(action(first,'hechizo',{uid:'spell',casilla:5}),/espacio/);
  d=await action(first,'hechizo',{uid:'spell',casilla:4});
  assert.equal(d.yo.apoyos[4].id,'hechizo-invisibilidad');
  assert.deepEqual((await view(ale)).rival.apoyos[4],{oculta:true});
  d=await action(first,'atacar',{casilla:0,objetivo:0});
  assert.equal(d.turno,'a');assert.equal(d.ronda,2);assert.equal(d.rival.vida,2000);
  assert.equal(d.yo.campo[0].ataco,true);
  await assert.rejects(action(first,'atacar',{casilla:0}),/no puede atacar/);
  d=await action(first,'posicion',{casilla:0});
  assert.equal(d.yo.campo[0].ataco,true);
  await assert.rejects(action(first,'atacar',{casilla:0}),/no puede atacar/);
  d=await action(first,'atacar',{casilla:1});
  assert.equal(d.rival.vida,900);assert.equal(d.turno,'a');assert.equal(d.ronda,2);
  assert.equal(d.yo.campo[2].posicion,'defensa');
  d=await action(first,'atacar',{casilla:2});
  assert.equal(d.yo.campo[2].posicion,'ataque');assert.equal(d.yo.campo[2].ataco,true);
  assert.equal(d.estado,'finalizado');
  await assert.rejects(action(first,'atacar',{casilla:1}),/ya terminó/);
 }finally{await db.close();}
});