import assert from 'node:assert/strict';
import { test } from 'node:test';
import { pathToFileURL } from 'node:url';
import { createServer } from 'vite';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');

test('touch fan: browse, release, cancel, corners and hidden opponent hand', async () => {
  const server = await createServer({ server: { host: '127.0.0.1', port: 0 } });
  let browser;
  try {
    await server.listen();
    browser = await chromium.launch({ headless: true, executablePath: process.env.EDGE_PATH });
    const page = await browser.newPage({ viewport: { width: 390, height: 700 }, hasTouch: true, isMobile: true });
    await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/tests/ui/arena.html`);
    await page.locator('.duel-hand .duel-card').first().waitFor();
    assert.equal(await page.locator('.duel-hint').count(), 0);
    assert.equal(await page.locator('.duel-rival-hand img').count(), 5);
    assert.ok(await page.locator('.duel-rival-hand img').evaluateAll(images => images.every(img => img.getAttribute('src') === '/hechi/card-back.png')));
    const rival = await page.locator('.duel-hud-player.rival').boundingBox();
    const own = await page.locator('.duel-own-life').boundingBox();
    assert.ok(rival.x < 20 && rival.y < 20 && own.x > 195 && own.y > 350);
    const centers = await page.locator('.duel-hand .duel-card').evaluateAll(cards => cards.map(card => {
      const box = card.getBoundingClientRect();
      return { x: box.x + box.width / 2, y: box.y + box.height / 2 };
    }));
    const cdp = await page.context().newCDPSession(page);
    const touch = (type, point) => cdp.send('Input.dispatchTouchEvent', { type, touchPoints: point ? [{ ...point, id: 1 }] : [] });
    await touch('touchStart', centers[0]);
    await touch('touchMove', centers[1]);
    await page.locator('[data-uid="two"].is-browsing').waitFor();
    assert.equal(await page.locator('.duel-hand .is-selected').count(), 0, 'browsing does not select every crossed card');
    await touch('touchMove', centers[2]);
    await page.locator('[data-uid="three"].is-browsing').waitFor();
    await touch('touchEnd');
    await page.locator('[data-uid="three"].is-selected').waitFor();
    assert.equal(await page.locator('.duel-hand .is-selected').count(), 1);
    assert.equal(await page.evaluate(() => window.arenaCalls.filter(c => c.method === 'accion_duelo_arena').length), 0);
    assert.equal(await page.locator('.duel-card-preview').count(),0);
    await touch('touchStart', centers[0]);
    await touch('touchMove', centers[1]);
    await touch('touchCancel');
    assert.equal(await page.locator('.duel-hand .is-browsing').count(), 0);
    assert.equal(await page.locator('[data-uid="three"].is-selected').count(), 1, 'cancelling keeps the original selection');
    for (const [width, height] of [[320,568],[390,700],[430,932],[844,390],[1280,900]]) {
      await page.setViewportSize({ width, height });
      await page.waitForTimeout(180);
      const boxes = await page.locator('.duel-hand .duel-card').evaluateAll(cards => cards.map(card => card.getBoundingClientRect().toJSON()));
      assert.ok(boxes.every(box => box.left >= 0 && box.right <= width && box.bottom <= height), `fan fits ${width}x${height}`);
    }
    await page.setViewportSize({ width: 390, height: 700 });
    await page.waitForFunction(() => !document.querySelector('.duel-intro-toast'), null, { timeout: 11000 });
    await page.getByRole('button', { name: 'Invocar en espacio 1', exact: true }).click();
    await page.getByRole('button', { name: 'Colocar boca arriba', exact: true }).click();
    assert.equal(await page.locator('.duel-intro-toast').count(), 0, 'summoning does not replay the introduction');
    await page.reload();
    await page.locator('.duel-hand [data-uid="one"]').waitFor();
    const source=await page.locator('.duel-hand [data-uid="one"]').boundingBox();
    const destination=await page.getByRole('button',{name:'Invocar en espacio 3',exact:true}).boundingBox();
    await touch('touchStart',{x:source.x+source.width/2,y:source.y+source.height/2});
    await touch('touchMove',{x:source.x+source.width/2,y:source.y+source.height/2-25});
    await page.locator('.duel-drag-ghost .duel-card-face').waitFor();
    assert.equal(await page.locator('.duel-drag-ghost .duel-card-stats b').count(),2,'drag includes the full card and statistics');
    await touch('touchMove',{x:destination.x+destination.width/2,y:destination.y+destination.height/2});
    await touch('touchEnd');
    await page.getByRole('dialog',{name:'Colocar carta'}).waitFor();
    assert.equal(await page.locator('.duel-placement-flip .duel-card-face').count(),1);
    await page.getByRole('button',{name:'Girar carta',exact:true}).click();
    assert.equal(await page.locator('.duel-placement-flip').getAttribute('data-face'),'down');
    await page.getByRole('button',{name:'Girar carta',exact:true}).click();
    assert.equal(await page.locator('.duel-placement-flip').getAttribute('data-face'),'up');
    if(process.env.PLACEMENT_SCREENSHOT) await page.screenshot({path:process.env.PLACEMENT_SCREENSHOT});
    assert.equal(await page.evaluate(()=>window.arenaCalls.filter(c=>c.method==='accion_duelo_arena').length),0,'drop must not play before confirmation');
    assert.equal(await page.locator('.duel-card-preview, .duel-selection-options, select').count(),0);
    await page.getByRole('button',{name:'Cancelar',exact:true}).click();
    assert.equal(await page.evaluate(()=>window.arenaCalls.filter(c=>c.method==='accion_duelo_arena').length),0);
    await page.getByRole('button',{name:'Invocar en espacio 3',exact:true}).click();
  await page.getByRole('button',{name:'Girar carta a la derecha',exact:true}).click();
    await page.getByRole('button',{name:'Colocar boca abajo',exact:true}).click();
    const move=await page.evaluate(()=>window.arenaCalls.filter(c=>c.method==='accion_duelo_arena').at(-1));
    assert.equal(move.args.p_datos.casilla,2);assert.equal(move.args.p_datos.oculta,true);assert.equal(move.args.p_datos.posicion,'ataque');
    assert.ok(move.args.p_datos.afinidad);
    await page.getByRole('button',{name:'Menú del duelo',exact:true}).click();
    await page.getByRole('button',{name:'Salir al listado de retos',exact:true}).click();
    await page.getByRole('searchbox',{name:'Buscar rival'}).fill('maria');
    assert.equal(await page.locator('.duel-rivals > div').count(),1);
    await page.getByRole('searchbox',{name:'Buscar rival'}).fill('no existe');
    await page.getByText('No hay jugadores con ese nombre.',{exact:true}).waitFor();
    await page.getByRole('searchbox',{name:'Buscar rival'}).fill('');
    assert.equal(await page.locator('.duel-rivals > div').count(),3);
    if (process.env.ARENA_SCREENSHOT) await page.screenshot({ path: process.env.ARENA_SCREENSHOT });
  } finally {
    await browser?.close();
    await server.close();
  }
});
