-- Generated catalog from src/data/duelCatalog.json; stats are authoritative on the server.
insert into hechi.cartas_arena(id,ataque,defensa,copias,afinidades) values
('bowtruckle',800,1400,4,array['tierra','luz']),
('doxy',1100,700,4,array['aire','sombra']),
('duendecillo',1000,1000,4,array['aire','fuego']),
('elfo',900,1200,4,array['luz','tierra']),
('lechuza',700,1300,4,array['aire','luz']),
('acromantula',1600,1200,3,array['sombra','tierra']),
('centauro',1700,1400,3,array['tierra','luz']),
('demiguise',1200,1900,3,array['luz','aire']),
('dugbog',1500,1700,3,array['agua','tierra']),
('escarbato',1300,1800,3,array['tierra','sombra']),
('fwooper',1600,1300,3,array['aire','fuego']),
('grindylow',1700,1200,3,array['agua','sombra']),
('basilisco',2300,1800,2,array['sombra','tierra']),
('cerbero',2200,2100,2,array['fuego','sombra']),
('dementor',2100,2300,2,array['sombra','aire']),
('gigante',2400,1700,2,array['tierra','fuego']),
('hipogrifo',2200,1900,2,array['aire','luz']),
('hombre-lobo',2300,1600,2,array['sombra','tierra']),
('inferi',1900,2400,2,array['sombra','agua']),
('thestral',2100,2200,2,array['aire','sombra']),
('dragon',2800,2300,1,array['fuego','aire']),
('fenix',2500,2600,1,array['fuego','luz']),
('troll',2700,2400,1,array['tierra','sombra']),
('unicornio',2400,2800,1,array['luz','agua'])
on conflict(id) do update set ataque=excluded.ataque,defensa=excluded.defensa,copias=excluded.copias,afinidades=excluded.afinidades;
insert into hechi.fusiones_arena(receta,resultado) values
('bowtruckle+doxy','acromantula'),
('bowtruckle+elfo','centauro'),
('elfo+lechuza','demiguise'),
('bowtruckle+duendecillo','dugbog'),
('duendecillo+elfo','escarbato'),
('doxy+lechuza','fwooper'),
('doxy+duendecillo','grindylow'),
('acromantula+dugbog','basilisco'),
('centauro+duendecillo','cerbero'),
('demiguise+doxy','dementor'),
('bowtruckle+escarbato','gigante'),
('centauro+lechuza','hipogrifo'),
('centauro+doxy','hombre-lobo'),
('elfo+grindylow','inferi'),
('demiguise+fwooper','thestral'),
('basilisco+fwooper','dragon'),
('fwooper+hipogrifo','fenix'),
('dugbog+gigante','troll'),
('demiguise+thestral','unicornio')
on conflict(receta) do update set resultado=excluded.resultado;
